In [6]:
import pandas as pd
coeffs = pd.read_csv('coefficients.csv')
coeffs.head(15)

           Features  Coefficients  AbsCoefficients
0            Airbed  7.610310e+13     7.610310e+13
1             Couch  7.610310e+13     7.610310e+13
2          Real Bed  7.610310e+13     7.610310e+13
3     Pull-out Sofa  7.610310e+13     7.610310e+13
4             Futon  7.610310e+13     7.610310e+13
5   Entire home/apt  5.981072e+13     5.981072e+13
6      Private room  5.981072e+13     5.981072e+13
7       Shared room  5.981072e+13     5.981072e+13
8         Northgate -1.591061e+13     1.591061e+13
9    Rainier Valley -1.591061e+13     1.591061e+13
10         Interbay -1.591061e+13     1.591061e+13
11         Delridge -1.591061e+13     1.591061e+13
12      Beacon Hill -1.591061e+13     1.591061e+13
13      Seward Park -1.591061e+13     1.591061e+13
14        Lake City -1.591061e+13     1.591061e+13